<a href="https://colab.research.google.com/github/julichitai/learning_NN/blob/MIPT/mipt_%5Bseminar%5Dpytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>"Глубокое обучение". Продвинутый поток</b></h3>

<h2 style="text-align: center;"><b>Семинар 6. Основы библиотеки PyTorch </b></h2>


# PyTorch basics: syntax, torch.cuda and torch.autograd</b></h2>

<p style="align: center;"><img src="https://upload.wikimedia.org/wikipedia/commons/9/96/Pytorch_logo.png" width=400 height=100></p>

Hi! In this notebook we will cover the basics of the **PyTorch deep learning framework**. 

https://youtu.be/aW9BgoKalY0

<h3 style="text-align: center;"><b>Intro</b></h3>

**Frameworks** are the specific code libraries with their own internal structure and pipelines.

There are many deep learning frameworks nowadays (02/2019). The difference between them is in the internal computation principles. For example, in **[Caffe](http://caffe.berkeleyvision.org/)** and **[Caffe2](https://caffe2.ai/)** you write the code using some "ready blocks" (just like the $LEGO^{TM}$ :). In **[TensorFlow](https://www.tensorflow.org/)** and **[Theano](http://deeplearning.net/software/theano/)** you declare the computation graph at first, then compile it and use it for inference/training (`tf.session()`). By the way, now TensorFlow (since v1.10) has the [Eager Execution](https://www.tensorflow.org/guide/eager), which can be handy for fast prototyping and debugging. **[Keras](https://keras.io/)** is a very popular and useful DL framework that allows to create networks fast and has many demanding features. 

<p style="align: center;"><img src="https://habrastorage.org/web/e3e/c3e/b78/e3ec3eb78d714a7993a6b922911c0866.png" width=500 height=500></p>  
<p style="text-align: center;"><i>Image credit: https://habr.com/post/334380/</i><p>

We will use PyTorch bacause it's been actively developed and supported by the community and [Facebook AI Research](https://research.fb.com/category/facebook-ai-research/).

<h3 style="text-align: center;"><b>Installation</b></h3>

The detailed instruction on how to install PyTorch you can find on the [official PyTorch website](https://pytorch.org/).

## Syntax

In [1]:
import torch

Some facts about PyTorch:  
- dynamic computation graph
- handy `torch.nn` and `torchvision` modules for fast neural network prototyping
- even faster than TensorFlow on some tasks
- allows to use GPU easily

At its core, PyTorch provides two main features:

- An n-dimensional Tensor, similar to numpy but can run on GPUs
- Automatic differentiation for building and training neural networks

If PyTorch was a formula, it would be:  

$$PyTorch = NumPy + CUDA + Autograd$$

(CUDA - [wiki](https://en.wikipedia.org/wiki/CUDA))

Let's see how we can use PyTorch to operate with vectors and tensors.  

Recall that **a tensor** is a multidimensional vector, e.g. :  

`x = np.array([1,2,3])` -- a vector = a tensor with 1 dimension (to be more precise: `(3,)`)  
`y = np.array([[1, 2, 3], [4, 5, 6]])` -- a matrix = a tensor with 2 dimensions (`(2, 3)` in this case)  
`z = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  
               [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])` -- "a cube" (3, 3, 3) = a tensor with 3 dimensions (`(3, 3, 3)` in this case)

One real example of 3-dimensional tensor is **an image**, it has 3 dimensions: `height`, `width` and the `channel depth` (= 3 for color images, 1 for a greyscale). You can think of it as of parallelepiped consisting of the real numbers.

In PyTorch we will use `torch.Tensor` (`FloatTensor`, `IntTensor`, `ByteTensor`) for all the computations.

All tensor types:

In [2]:
torch.HalfTensor      # 16 бит, floating point
torch.FloatTensor     # 32 бита, floating point
torch.DoubleTensor    # 64 бита, floating point

torch.ShortTensor     # 16 бит, integer, signed
torch.IntTensor       # 32 бита, integer, signed
torch.LongTensor      # 64 бита, integer, signed

torch.CharTensor      # 8 бит, integer, signed
torch.ByteTensor      # 8 бит, integer, unsigned

torch.ByteTensor

We will use only `torch.FloatTensor()` and `torch.IntTensor()`. 

Let's begin to do something!

* Creating the tensor:

In [3]:
a = torch.FloatTensor([1, 2])
a


tensor([1., 2.])

In [4]:
a.shape

torch.Size([2])

In [5]:
b = torch.FloatTensor([[1,2,3], [4,5,6]])
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [6]:
b.shape

torch.Size([2, 3])

In [7]:
x = torch.FloatTensor(2,3,4)

In [8]:
x

tensor([[[8.3752e-36, 0.0000e+00, 7.0065e-44, 6.8664e-44],
         [6.3058e-44, 6.7262e-44, 6.8664e-44, 6.3058e-44],
         [7.0065e-44, 7.2868e-44, 1.1771e-43, 6.7262e-44]],

        [[7.7071e-44, 8.1275e-44, 7.2868e-44, 7.5670e-44],
         [8.1275e-44, 7.1466e-44, 7.7071e-44, 6.4460e-44],
         [7.4269e-44, 7.2868e-44, 7.7071e-44, 7.7071e-44]]])

In [9]:
x = torch.FloatTensor(100)
x

tensor([ 3.2609e-36,  0.0000e+00,  1.4396e-38,  0.0000e+00,  5.8154e-43,
         0.0000e+00,         nan,         nan,  4.4721e+21,  2.3079e+20,
         6.2689e+22,  4.7428e+30,  1.3563e-19,  1.3817e-19, -1.0752e+10,
        -9.9222e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,  1.8061e+28,
         7.5527e+28,  5.2839e-11,  2.7604e+20,  1.7744e+28,  2.0535e-19,
         1.3563e-19,  1.0426e-08, -2.3866e+10, -1.7558e+10,  1.8910e+23,
         7.1443e+31,  1.9603e-19,  1.8061e+28,  7.5527e+28,  5.2839e-11,
         1.1319e+21,  6.2688e+22,  4.7428e+30,  1.3563e-19,  1.6962e-07,
        -2.3866e+10, -1.7558e+10,  1.8910e+23,  7.1443e+31,  1.9603e-19,
         1.8061e+28,  4.3747e+31,  4.2964e+24,  7.1901e+28,  6.2706e+22,
         4.7428e+30,  1.3563e-19,  2.3303e-09, -6.0573e-09, -3.0816e-37,
         1.8037e+28,  6.8296e+22,  1.2690e+31,  7.0364e+22,  7.5527e+28,
         5.2839e-11,  4.1993e+12,  7.5338e+28,  1.3563e-19,  1.3563e-19,
         1.0426e-08, -2.3866e+10, -1.7558e+10,  1.2

In [10]:
x = torch.IntTensor(45, 57, 14, 2)
x.shape

torch.Size([45, 57, 14, 2])

**Note:** if you create `torch.Tensor` with the following constructor it will be filled with the "random trash numbers":

In [11]:
x = torch.IntTensor(3, 2, 4)
x

tensor([[[87170816,        0,       50,       49],
         [      45,       48,       49,       45]],

        [[      50,       52,       84,       48],
         [      55,       58,       52,       54]],

        [[      58,       51,       55,       46],
         [      53,       57,       55,       48]]], dtype=torch.int32)

Here is a way to fill a new tensor with zeroes:

In [12]:
x1 = torch.FloatTensor(3, 2, 4)
x1.zero_()
x2 = torch.zeros(3, 2, 4)
x3 = torch.zeros_like(x1)

assert torch.allclose(x1, x2) and torch.allclose(x1, x3)
x1

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Random distribution initialization

In [13]:
x = torch.randn((2,3))                # Normal(0, 1) with shape
x

tensor([[-1.4431,  1.0656,  0.5158],
        [-0.4010,  0.4336, -0.6314]])

In [14]:
x.random_(0, 10)                      # discrete U[0, 10]
x.uniform_(0, 1)                      # U[0, 1]
x.normal_(mean=0, std=1)              # Normal with mean and std
x.bernoulli_(p=0.5)                   # bernoulli with parameter p

tensor([[0., 0., 1.],
        [1., 1., 0.]])

## Numpy -> Torch

All numpy function have its pair in torch.

https://github.com/torch/torch7/wiki/Torch-for-Numpy-users

`np.reshape()` == `torch.view()`:

In [15]:
b, b.stride()

(tensor([[1., 2., 3.],
         [4., 5., 6.]]), (3, 1))

In [16]:
b.view(3, 2), b.view(3, 2).stride()  

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]), (2, 1))

**Note:** `torch.view()` creates a new tensor, one the old one remains unchanged

In [17]:
b.view(-1)

tensor([1., 2., 3., 4., 5., 6.])

In [18]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
b.T.stride(), b.is_contiguous(), b.T.is_contiguous()

((1, 3), True, False)

In [20]:
b.reshape(-1) # returns view or contigues tensor

tensor([1., 2., 3., 4., 5., 6.])

In [21]:
b

tensor([[1., 2., 3.],
        [4., 5., 6.]])

* Change a tensor type:

In [20]:
a = torch.FloatTensor([1.5, 3.2, -7])

In [21]:
a.type_as(torch.IntTensor())

tensor([ 1,  3, -7], dtype=torch.int32)

In [22]:
a.to(torch.int32)

tensor([ 1,  3, -7], dtype=torch.int32)

In [23]:
a.type_as(torch.ByteTensor())

tensor([  1,   3, 249], dtype=torch.uint8)

In [24]:
a.to(torch.uint8)

tensor([  1,   3, 249], dtype=torch.uint8)

**Note:** `.type_as()` creates a new tensor, the old one remains unchanged

In [25]:
a

tensor([ 1.5000,  3.2000, -7.0000])

* Indexing is just like in `NumPy`:

In [26]:
a = torch.FloatTensor([[100, 20, 35], [15, 163, 534], [52, 90, 66]])
a

tensor([[100.,  20.,  35.],
        [ 15., 163., 534.],
        [ 52.,  90.,  66.]])

In [27]:
a[0, 0]

tensor(100.)

In [28]:
a[0:2, 1]

tensor([ 20., 163.])

**Ariphmetics and boolean operations** and their analogues:  

| Operator | Analogue |
|:-:|:-:|
|`+`| `torch.add()` |
|`-`| `torch.sub()` |
|`*`| `torch.mul()` |
|`/`| `torch.div()` |

* Addition:

In [29]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [30]:
a + b

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [31]:
a.add(b)

tensor([[  0.,   0.,   0.],
        [  0.,   0.,   0.],
        [200., 400., 600.]])

In [32]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [33]:
a + b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

* Subtraction:

In [34]:
a - b

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [35]:
a.sub(b) # copy

tensor([[  2.,   4.,   6.],
        [ 20.,  40.,  60.],
        [200., 400., 600.]])

In [37]:
a.sub_(b) # inplace

tensor([[  3.,   6.,   9.],
        [ 30.,  60.,  90.],
        [300., 600., 900.]])

* Multiplication (elementwise):

In [38]:
a * b

tensor([[-3.0000e+00, -1.2000e+01, -2.7000e+01],
        [-3.0000e+02, -1.2000e+03, -2.7000e+03],
        [-3.0000e+04, -1.2000e+05, -2.7000e+05]])

In [39]:
a.mul(b)

tensor([[-3.0000e+00, -1.2000e+01, -2.7000e+01],
        [-3.0000e+02, -1.2000e+03, -2.7000e+03],
        [-3.0000e+04, -1.2000e+05, -2.7000e+05]])

* Division (elementwise):

In [40]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [41]:
a / b

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

In [42]:
a.div(b)

tensor([[-1., -1., -1.],
        [-1., -1., -1.],
        [ 1.,  1.,  1.]])

**Note:** all this operations create new tensors, the old tensors remain unchanged

In [43]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [44]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

* Comparison operators:

In [45]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [46]:
a == b

tensor([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [47]:
a != b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

In [48]:
a < b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [49]:
a > b

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

* Using boolean mask indexing:

In [50]:
a[a > b]

tensor([ 1.,  2.,  3., 10., 20., 30.])

In [51]:
b[a == b]

tensor([100., 200., 300.])

Elementwise application of the **universal functions**:

In [52]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])

In [53]:
a.sin()

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [54]:
torch.sin(a)

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.5440,  0.9129, -0.9880],
        [-0.5064, -0.8733, -0.9998]])

In [55]:
a.tan()

tensor([[ 1.5574, -2.1850, -0.1425],
        [ 0.6484,  2.2372, -6.4053],
        [-0.5872, -1.7925, 45.2447]])

In [56]:
a.exp()

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01],
        [2.2026e+04, 4.8517e+08, 1.0686e+13],
        [       inf,        inf,        inf]])

In [57]:
a.log()

tensor([[0.0000, 0.6931, 1.0986],
        [2.3026, 2.9957, 3.4012],
        [4.6052, 5.2983, 5.7038]])

In [58]:
b = -a
b

tensor([[  -1.,   -2.,   -3.],
        [ -10.,  -20.,  -30.],
        [-100., -200., -300.]])

In [59]:
b.abs()

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* The sum, mean, max, min:

In [60]:
a.sum(dim=1)

tensor([  6.,  60., 600.])

In [61]:
a.mean()

tensor(74.)

Along axis:

In [62]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [63]:
a.sum(dim=0)

tensor([111., 222., 333.])

In [64]:
a.sum(1)

tensor([  6.,  60., 600.])

In [65]:
a.max()

tensor(300.)

In [66]:
a.max(0)

torch.return_types.max(values=tensor([100., 200., 300.]), indices=tensor([2, 2, 2]))

In [67]:
a.min()

tensor(1.)

In [68]:
a.min(0)

torch.return_types.min(values=tensor([1., 2., 3.]), indices=tensor([0, 0, 0]))

**Note:** the second tensor returned by `.max()` and `.min()` contains the indices of max/min elements along this axis. E.g. in that case `a.min()` returned `(1, 2, 3)` which are the minimum elements along 0 axis (along columns) and their indices along 0 axis are `(0, 0, 0)`.

**Matrix operations**:

* Transpose a tensor:

In [69]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [70]:
a.t()

tensor([[  1.,  10., 100.],
        [  2.,  20., 200.],
        [  3.,  30., 300.]])

It is not not the inplace operation too:

In [71]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

* Dot product of vectors:

In [72]:
a = torch.FloatTensor([1, 2, 3, 4, 5, 6])
b = torch.FloatTensor([-1, -2, -4, -6, -8, -10])

In [73]:
a.dot(b)

tensor(-141.)

In [74]:
a.shape, b.shape

(torch.Size([6]), torch.Size([6]))

In [75]:
a @ b

tensor(-141.)

In [76]:
type(a)

torch.Tensor

In [77]:
type(b)

torch.Tensor

In [78]:
type(a @ b)

torch.Tensor

* Matrix product:

In [79]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1, -2, -3], [-10, -20, -30], [100, 200, 300]])

In [80]:
a.mm(b)

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

In [81]:
a @ b

tensor([[  279.,   558.,   837.],
        [ 2790.,  5580.,  8370.],
        [27900., 55800., 83700.]])

Remain unchanged:

In [82]:
a

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]])

In [83]:
b

tensor([[ -1.,  -2.,  -3.],
        [-10., -20., -30.],
        [100., 200., 300.]])

In [84]:
a = torch.FloatTensor([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
b = torch.FloatTensor([[-1], [-10], [100]])

In [85]:
print(a.shape, b.shape)

torch.Size([3, 3]) torch.Size([3, 1])


In [86]:
a @ b

tensor([[  279.],
        [ 2790.],
        [27900.]])

If we unroll the tensor `b` in an array (`torch.view(-1)`) the multiplication would be like with the column:

In [87]:
b

tensor([[ -1.],
        [-10.],
        [100.]])

In [88]:
b.view(-1)

tensor([ -1., -10., 100.])

In [89]:
a @ b.view(-1)

tensor([  279.,  2790., 27900.])

In [90]:
a.mv(b.view(-1))

tensor([  279.,  2790., 27900.])

In [91]:
y = torch.Tensor(2, 3, 4, 5)
z = torch.Tensor(2, 3, 5, 6)
(y @ z).shape

torch.Size([2, 3, 4, 6])

**From NumPu to PyTorch conversion**:

In [92]:
import numpy as np

a = np.random.rand(3, 3)
a

array([[0.41008103, 0.60539465, 0.4483608 ],
       [0.26015056, 0.27474605, 0.3096673 ],
       [0.05233577, 0.09387276, 0.20398469]])

In [93]:
b = torch.from_numpy(a)
b

tensor([[0.4101, 0.6054, 0.4484],
        [0.2602, 0.2747, 0.3097],
        [0.0523, 0.0939, 0.2040]], dtype=torch.float64)

**NOTE!** `a` and `b` have the same data storage, so the changes in one tensor will lead to the changes in another:

In [94]:
b -= b
b

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [95]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**From PyTorch to NumPy conversion:**

In [96]:
a = torch.FloatTensor(2, 3, 4)
a

tensor([[[8.3761e-36, 0.0000e+00, 7.0065e-44, 6.8664e-44],
         [6.3058e-44, 6.7262e-44, 6.8664e-44, 6.3058e-44],
         [7.0065e-44, 7.2868e-44, 1.1771e-43, 6.7262e-44]],

        [[7.7071e-44, 8.1275e-44, 7.4269e-44, 7.7071e-44],
         [8.1275e-44, 6.8664e-44, 7.2868e-44, 6.4460e-44],
         [7.2868e-44, 7.1466e-44, 7.7071e-44, 7.1466e-44]]])

In [97]:
type(a)

torch.Tensor

In [98]:
x = a.numpy()
x

array([[[8.376132e-36, 0.000000e+00, 7.006492e-44, 6.866362e-44],
        [6.305843e-44, 6.726233e-44, 6.866362e-44, 6.305843e-44],
        [7.006492e-44, 7.286752e-44, 1.177091e-43, 6.726233e-44]],

       [[7.707142e-44, 8.127531e-44, 7.426882e-44, 7.707142e-44],
        [8.127531e-44, 6.866362e-44, 7.286752e-44, 6.445973e-44],
        [7.286752e-44, 7.146622e-44, 7.707142e-44, 7.146622e-44]]],
      dtype=float32)

In [99]:
x.shape

(2, 3, 4)

In [100]:
type(x)

numpy.ndarray

In [101]:
x -= x

In [102]:
a

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

Let's write the `forward_pass(X, w)` ($w_0$ is a part of the $w$) for a single neuron (activation = sigmoid) using PyTorch:

In [103]:
def forward_pass(X, w):
    return torch.sigmoid(X @ w)

In [104]:
X = torch.FloatTensor([[-5, 5], [2, 3], [1, -1]])
w = torch.FloatTensor([[-0.5], [2.5]])
result = forward_pass(X, w)
print('result: {}'.format(result))

result: tensor([[1.0000],
        [0.9985],
        [0.0474]])


## <h1 style="text-align: center;"><a href="https://ru.wikipedia.org/wiki/CUDA">CUDA</a></h3>

[CUDA documentation](https://docs.nvidia.com/cuda/)

We can use both CPU (Central Processing Unit) and GPU (Graphical Processing Unit) to make the computations with PyTorch. We can switch between them easily, this is one of the most important things in PyTorch framework.

In [105]:
x = torch.FloatTensor(1024, 10024).uniform_()
x

tensor([[0.1033, 0.8269, 0.6391,  ..., 0.3381, 0.1414, 0.5972],
        [0.0645, 0.5934, 0.3038,  ..., 0.2678, 0.2448, 0.2763],
        [0.8848, 0.1349, 0.7465,  ..., 0.2547, 0.5932, 0.1564],
        ...,
        [0.5915, 0.1461, 0.9786,  ..., 0.4133, 0.9202, 0.2622],
        [0.1910, 0.7695, 0.0840,  ..., 0.9998, 0.5286, 0.7368],
        [0.9377, 0.3473, 0.5821,  ..., 0.0148, 0.8610, 0.9154]])

In [106]:
x.is_cuda

False

Place a tensor on GPU (GPU memory is used):

In [107]:
!nvidia-smi

Sun Jan 24 07:59:04 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [108]:
x = x.cuda()

In [109]:
!nvidia-smi

Sun Jan 24 07:59:20 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   40C    P0    26W /  70W |    989MiB / 15079MiB |      4%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [113]:
x

tensor([[0.1033, 0.8269, 0.6391,  ..., 0.3381, 0.1414, 0.5972],
        [0.0645, 0.5934, 0.3038,  ..., 0.2678, 0.2448, 0.2763],
        [0.8848, 0.1349, 0.7465,  ..., 0.2547, 0.5932, 0.1564],
        ...,
        [0.5915, 0.1461, 0.9786,  ..., 0.4133, 0.9202, 0.2622],
        [0.1910, 0.7695, 0.0840,  ..., 0.9998, 0.5286, 0.7368],
        [0.9377, 0.3473, 0.5821,  ..., 0.0148, 0.8610, 0.9154]])

In [112]:
x = x.cpu()
!nvidia-smi

torch.cuda.empty_cache()
!nvidia-smi

Sun Jan 24 08:01:35 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    27W /  70W |    989MiB / 15079MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [114]:
device = torch.device("cuda:0")
x = x.to(device)
x

tensor([[0.1033, 0.8269, 0.6391,  ..., 0.3381, 0.1414, 0.5972],
        [0.0645, 0.5934, 0.3038,  ..., 0.2678, 0.2448, 0.2763],
        [0.8848, 0.1349, 0.7465,  ..., 0.2547, 0.5932, 0.1564],
        ...,
        [0.5915, 0.1461, 0.9786,  ..., 0.4133, 0.9202, 0.2622],
        [0.1910, 0.7695, 0.0840,  ..., 0.9998, 0.5286, 0.7368],
        [0.9377, 0.3473, 0.5821,  ..., 0.0148, 0.8610, 0.9154]],
       device='cuda:0')

Let's multiply two tensors on GPU and then move the result on the CPU:

In [115]:
a = torch.FloatTensor(10000, 10000).uniform_()
b = torch.FloatTensor(10000, 10000).uniform_()
c = a.cuda().mul(b.cuda()).cpu()

In [116]:
c

tensor([[0.4542, 0.6463, 0.0415,  ..., 0.4853, 0.0051, 0.3724],
        [0.3026, 0.7142, 0.5476,  ..., 0.0740, 0.5755, 0.2842],
        [0.0628, 0.1770, 0.1862,  ..., 0.0436, 0.7516, 0.5041],
        ...,
        [0.0864, 0.0458, 0.0766,  ..., 0.4913, 0.3365, 0.0692],
        [0.2517, 0.0643, 0.0907,  ..., 0.0134, 0.2832, 0.0490],
        [0.1022, 0.1439, 0.0085,  ..., 0.2194, 0.0075, 0.1413]])

In [117]:
a

tensor([[0.9926, 0.7076, 0.1192,  ..., 0.9631, 0.1362, 0.9744],
        [0.4227, 0.8228, 0.5947,  ..., 0.0928, 0.8844, 0.3200],
        [0.0759, 0.2142, 0.4245,  ..., 0.1814, 0.8860, 0.9200],
        ...,
        [0.4195, 0.3688, 0.2032,  ..., 0.7351, 0.3688, 0.3894],
        [0.9606, 0.2562, 0.5966,  ..., 0.3228, 0.5876, 0.1715],
        [0.9411, 0.6005, 0.5624,  ..., 0.5365, 0.0389, 0.8043]])

Tensors placed on CPU and tensors placed on GPU are unavailable for each other:

In [118]:
a = torch.FloatTensor(10000, 10000).uniform_().cpu()
b = torch.FloatTensor(10000, 10000).uniform_().cuda()

In [119]:
a + b

RuntimeError: ignored

Example of working with GPU:

In [120]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [121]:
x = torch.FloatTensor(5, 5, 5).uniform_()

# check for CUDA availability (NVIDIA GPU)
if torch.cuda.is_available():
    # get the CUDA device name
    device = torch.device('cuda')          # CUDA-device object
    y = torch.ones_like(x, device=device)  # create a tensor on GPU
    x = x.to(device)                       # or just `.to("cuda")`
    z = x + y
    print(z)
    # you can set the type while `.to` operation
    print(z.to("cpu", torch.double))

tensor([[[1.7388, 1.9235, 1.6752, 1.3629, 1.1430],
         [1.8727, 1.9386, 1.3222, 1.3722, 1.0790],
         [1.3230, 1.2318, 1.8966, 1.2765, 1.7202],
         [1.9786, 1.5042, 1.6265, 1.3318, 1.1096],
         [1.8180, 1.3490, 1.7771, 1.6606, 1.3454]],

        [[1.9912, 1.1283, 1.4942, 1.1380, 1.3485],
         [1.8592, 1.3432, 1.7691, 1.7480, 1.9695],
         [1.9932, 1.1941, 1.7667, 1.2844, 1.0491],
         [1.6807, 1.1094, 1.0341, 1.8662, 1.3928],
         [1.7581, 1.6453, 1.9734, 1.0510, 1.6270]],

        [[1.9853, 1.3877, 1.5058, 1.2847, 1.0869],
         [1.2688, 1.8484, 1.8130, 1.8318, 1.4942],
         [1.8187, 1.1712, 1.5287, 1.0522, 1.9530],
         [1.6712, 1.8732, 1.0444, 1.6723, 1.8586],
         [1.8956, 1.9980, 1.9736, 1.5638, 1.1081]],

        [[1.6174, 1.3411, 1.8577, 1.7273, 1.5024],
         [1.6497, 1.9756, 1.5201, 1.4441, 1.5990],
         [1.4243, 1.5111, 1.1884, 1.4059, 1.9257],
         [1.4015, 1.2407, 1.1246, 1.7164, 1.2498],
         [1.8451, 1.2823,

## AutoGrad

**Chain rule (a.k.a. backpropagation in NN)** used here

Assume we have $f(w(\theta))$
$${\frac  {\partial{f}}{\partial{\theta}}}
={\frac  {\partial{f}}{\partial{w}}}\cdot {\frac  {\partial{w}}{\partial{\theta}}}$$


*Additional reading: In multidimentional case it is described by composition of partial derivatives:*
$$
D_\theta(f\circ w) = D_{w(\theta)}(f)\circ D_\theta(w)
$$

Simple example of gradient propagation:

$$y = \sin \left(x_2^2(x_1 + x_2)\right)$$

<img src="https://ars.els-cdn.com/content/image/1-s2.0-S0010465515004099-gr1.jpg" width=700></img>


The autograd package provides automatic differentiation for all operations on Tensors. It is a define-by-run framework, which means that your backprop is defined by how your code is run, and that every single iteration can be different.

The examples:

In [123]:
dtype = torch.float
device = torch.device("cuda:0")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 3, 3, 10

# Create random Tensors to hold input and outputs.
# Setting requires_grad=False indicates that we do not need to compute gradients
# with respect to these Tensors during the backward pass.
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Create random Tensors for weights.
# Setting requires_grad=True indicates that we want to compute gradients with
# respect to these Tensors during the backward pass.
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

In [124]:
y_pred = (x @ w1).clamp(min=0).matmul(w2)
loss = (y_pred - y).pow(2).sum()
# calculate the gradients
loss.backward()

In [125]:
print((y_pred - y).pow(2).sum())

tensor(5207.9844, device='cuda:0', grad_fn=<SumBackward0>)


In [126]:
w1.grad, w2.grad

(tensor([[  425.3984,   495.8633,  -152.1935],
         [-1154.4331, -1075.4670,  1804.5427],
         [ -691.9756,  1092.6959,   415.1182]], device='cuda:0'),
 tensor([[-9.3202e+01, -3.1501e+02,  3.3615e+02, -2.0229e+02,  3.9670e+01,
          -3.9732e+02,  6.6360e+02,  2.5809e+02,  4.6462e+02, -2.4068e+02],
         [-4.4576e+02, -3.4906e+02,  3.8439e+02,  5.0529e-01, -1.6969e+02,
          -1.1056e+02,  2.4516e+02, -2.5365e+01,  1.7321e+02, -2.2201e+02],
         [-1.5747e+02, -2.7146e+02, -1.0332e+02,  5.4361e+02, -4.9663e+02,
           1.9261e+02,  7.8247e+01, -2.6349e+01, -2.4691e+01, -3.0192e+02]],
        device='cuda:0'))

In [127]:
loss.grad # can't access to non-leaf grad in AD tree

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  """Entry point for launching an IPython kernel.


In [128]:
# make the variable remember grad of loss
y_pred = (x @ w1).clamp(min=0).matmul(w2)
y_pred.retain_grad()

loss = (y_pred - y).pow(2).sum()
loss.retain_grad()

loss.backward()

In [129]:
loss.grad

tensor(1., device='cuda:0')

In [130]:
x.grad # doesn't require grad

In [131]:
y.grad # doesn't require grad

**NOTE:** the gradients are placed into the `.grad` field of tensors (variables) on which gradients were calculated. Gradients *are not placed* in the variable `loss` here!

In [132]:
w1

tensor([[ 0.8771,  0.5582,  0.0916],
        [-1.5943, -0.8411,  1.7612],
        [-1.4689,  1.1759,  0.6685]], device='cuda:0', requires_grad=True)

In [133]:
with torch.no_grad():
    pass

<h3 style="text-align: center;">Further reading:<b></b></h3>

*1). Official PyTorch tutorials: https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py*

*2). arXiv article about the deep learning frameworks comparison: https://arxiv.org/pdf/1511.06435.pdf*

*3). Useful repo with different tutorials: https://github.com/yunjey/pytorch-tutorial*

*4). Facebook AI Research (main contributor of PyTorch) website: https://facebook.ai/developers/tools*