<a href="https://colab.research.google.com/github/julichitai/learning_NN/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [5]:
torch.ones(3, 4, 2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [6]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [8]:
x.size(), x.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [11]:
display(x[0], x[0, 0], x[0][0], x[:, 0])

tensor([1., 2., 3., 4.])

tensor(1.)

tensor(1.)

tensor([1., 5., 9.])

In [12]:
x * 2

tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])

In [13]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [14]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [19]:
display(x + y, x * y, x % y)

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [22]:
display(torch.exp(y), torch.log(y), torch.sin(y))

tensor([[1.6275e+05, 5.9874e+04, 2.2026e+04, 8.1031e+03],
        [2.9810e+03, 1.0966e+03, 4.0343e+02, 1.4841e+02],
        [5.4598e+01, 2.0086e+01, 7.3891e+00, 2.7183e+00]])

tensor([[2.4849, 2.3979, 2.3026, 2.1972],
        [2.0794, 1.9459, 1.7918, 1.6094],
        [1.3863, 1.0986, 0.6931, 0.0000]])

tensor([[-0.5366, -1.0000, -0.5440,  0.4121],
        [ 0.9894,  0.6570, -0.2794, -0.9589],
        [-0.7568,  0.1411,  0.9093,  0.8415]])

In [24]:
mask = x > 3
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [25]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [28]:
import torch

X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = (X[X > limit]).sum()
larger_than_limit_sum

9


tensor(0)