<a href="https://colab.research.google.com/github/julichitai/learning_NN/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.zeros(3, 4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [3]:
torch.ones(3, 4, 2)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]])

In [4]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [5]:
x.size(), x.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [6]:
display(x[0], x[0, 0], x[0][0], x[:, 0])

tensor([1., 2., 3., 4.])

tensor(1.)

tensor(1.)

tensor([1., 5., 9.])

In [7]:
x * 2

tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])

In [8]:
x + 10

tensor([[11., 12., 13., 14.],
        [15., 16., 17., 18.],
        [19., 20., 21., 22.]])

In [9]:
y = torch.Tensor([[12, 11, 10, 9],
                  [8, 7, 6, 5],
                  [4, 3, 2, 1]])

In [10]:
display(x + y, x * y, x % y)

tensor([[13., 13., 13., 13.],
        [13., 13., 13., 13.],
        [13., 13., 13., 13.]])

tensor([[12., 22., 30., 36.],
        [40., 42., 42., 40.],
        [36., 30., 22., 12.]])

tensor([[1., 2., 3., 4.],
        [5., 6., 1., 3.],
        [1., 1., 1., 0.]])

In [11]:
display(torch.exp(y), torch.log(y), torch.sin(y))

tensor([[1.6275e+05, 5.9874e+04, 2.2026e+04, 8.1031e+03],
        [2.9810e+03, 1.0966e+03, 4.0343e+02, 1.4841e+02],
        [5.4598e+01, 2.0086e+01, 7.3891e+00, 2.7183e+00]])

tensor([[2.4849, 2.3979, 2.3026, 2.1972],
        [2.0794, 1.9459, 1.7918, 1.6094],
        [1.3863, 1.0986, 0.6931, 0.0000]])

tensor([[-0.5366, -1.0000, -0.5440,  0.4121],
        [ 0.9894,  0.6570, -0.2794, -0.9589],
        [-0.7568,  0.1411,  0.9093,  0.8415]])

In [12]:
mask = x > 3
x[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [13]:
x[x > 3]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [15]:
import torch

X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
limit = int(input())

larger_than_limit_sum = (X[X > limit]).sum()
larger_than_limit_sum

3


tensor(39)

In [16]:
y = x
y[0][0] = 999
display(x, y)

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [17]:
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

In [18]:
y = x.clone()
y[0][0] = 999
display(x, y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

tensor([[999.,   2.,   3.,   4.],
        [  5.,   6.,   7.,   8.],
        [  9.,  10.,  11.,  12.]])

In [19]:
x.dtype

torch.float32

In [20]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [21]:
import numpy as np
x = np.array([[1, 2, 3, 4],
              [4, 3, 2, 1]])
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [22]:
x = torch.from_numpy(x)
x

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [23]:
x = x.numpy()
x

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [24]:
x = torch.rand(2, 3)
x

tensor([[0.5929, 0.0109, 0.8917],
        [0.3562, 0.0114, 0.8215]])

In [25]:
torch.cuda.is_available()

True

In [26]:
torch.device('cuda')

device(type='cuda')

In [27]:
torch.device('cpu')

device(type='cpu')

In [28]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

device(type='cuda')

In [29]:
x_cuda = x.to(device)
x_cuda

tensor([[0.5929, 0.0109, 0.8917],
        [0.3562, 0.0114, 0.8215]], device='cuda:0')

In [32]:
%time y = (x - x + x * 10) ** 2

CPU times: user 653 µs, sys: 0 ns, total: 653 µs
Wall time: 392 µs


In [33]:
%time y = (x_cuda - x_cuda + x_cuda * 10) ** 2

CPU times: user 1.01 ms, sys: 0 ns, total: 1.01 ms
Wall time: 617 µs


Профит в производительности на GPU будет только с большими тензорами, только с большими данными получится увидеть в деле паралеллизм.

In [34]:
x = torch.rand(2000, 3000)
x

tensor([[0.0250, 0.5349, 0.6644,  ..., 0.5333, 0.3163, 0.3414],
        [0.9846, 0.8641, 0.7549,  ..., 0.5321, 0.5812, 0.9797],
        [0.0697, 0.4372, 0.3063,  ..., 0.6093, 0.4393, 0.6283],
        ...,
        [0.2093, 0.9127, 0.9945,  ..., 0.3575, 0.0664, 0.4915],
        [0.7808, 0.8130, 0.8305,  ..., 0.6568, 0.4465, 0.3695],
        [0.6567, 0.0135, 0.8906,  ..., 0.3712, 0.9257, 0.8658]])

In [36]:
%time y = (x - x + x * 10) ** 2

CPU times: user 19.6 ms, sys: 12 ms, total: 31.6 ms
Wall time: 32.5 ms


In [37]:
x_cuda = x.to(device)

In [38]:
%time y = (x_cuda - x_cuda + x_cuda * 10) ** 2

CPU times: user 1.98 ms, sys: 542 µs, total: 2.52 ms
Wall time: 1.94 ms
